# Generated by Django 4.2.6 on 2023-10-21 12:26

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.filepath),
        ),
    ]
