# Generated by Django 4.2.6 on 2023-10-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='confirmpassword',
            field=models.CharField(default=False, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='varified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
