# Generated by Django 4.2.6 on 2023-10-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_userprofile_confirmpassword_userprofile_varified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='confirmpassword',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
