# Generated by Django 4.2.6 on 2023-10-31 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_userprofile_confirmpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nid',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
