# Generated by Django 4.2.6 on 2023-11-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_userprofile_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='registerIP',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
