# Generated by Django 4.2.6 on 2023-11-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_userprofile_registerlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='registerLocation',
            field=models.TextField(default='', null=True),
        ),
    ]
