# Generated by Django 4.2.6 on 2023-11-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_mapmarker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapmarker',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mapmarker',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
