# Generated by Django 4.2.6 on 2023-11-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_userprofile_loginip_userprofile_loginlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('Thana', models.CharField(max_length=50, null=True)),
                ('last_login', models.CharField(max_length=1000, null=True)),
                ('loginIP', models.CharField(max_length=1000, null=True)),
                ('loginLocation', models.TextField(default='', null=True)),
            ],
        ),
    ]
