# Generated by Django 4.2.6 on 2023-11-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_adminprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='Thana',
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='District',
            field=models.CharField(choices=[('District1', 'District 1'), ('District2', 'District 2'), ('District3', 'District 3')], max_length=50, null=True),
        ),
    ]
