# Generated by Django 4.2.6 on 2023-11-08 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_adminprofile_thana_adminprofile_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='District',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.districtnames'),
        ),
    ]
