# Generated by Django 4.2.6 on 2023-11-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_physicalstructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='father_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
