# Generated by Django 4.2.6 on 2023-11-10 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_userprofile_father_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='father_name',
        ),
    ]
