# Generated by Django 4.2.6 on 2023-11-10 12:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_userprofile_father_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case_related',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.FileField(blank=True, null=True, upload_to=myapp.models.filepath)),
            ],
        ),
        migrations.RemoveField(
            model_name='physicalstructure',
            name='FrontFacedImage',
        ),
        migrations.RemoveField(
            model_name='physicalstructure',
            name='RightFacedImage',
        ),
        migrations.RemoveField(
            model_name='physicalstructure',
            name='criminal_id',
        ),
        migrations.RemoveField(
            model_name='physicalstructure',
            name='eyeColor',
        ),
        migrations.RemoveField(
            model_name='physicalstructure',
            name='leftFacedImage',
        ),
        migrations.AddField(
            model_name='physicalstructure',
            name='facialHair',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='physicalstructure',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='physicalstructure',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='physicalstructure',
            name='faceShape',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='physicalstructure',
            name='gender',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='physicalstructure',
            name='hairColor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='physicalstructure',
            name='hairLength',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='physicalstructure',
            name='hairStyle',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='physicalstructure',
            name='skinTone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='witnessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('relationWithVictim', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('nid', models.CharField(max_length=20, null=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='victimInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('fathername', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('nid', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('age', models.CharField(max_length=20, null=True)),
                ('division', models.CharField(max_length=50, null=True)),
                ('district', models.CharField(max_length=50, null=True)),
                ('upazila', models.CharField(max_length=50, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=myapp.models.filepath)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Case_description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_type', models.CharField(max_length=25, null=True)),
                ('occurance_date', models.DateField(null=True)),
                ('file_report_date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('division', models.CharField(max_length=50, null=True)),
                ('district', models.CharField(max_length=50, null=True)),
                ('upazila', models.CharField(max_length=50, null=True)),
                ('brief', models.TextField(null=True)),
                ('brief_material', models.TextField(null=True)),
                ('items', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.case_related')),
            ],
        ),
    ]
