# Generated by Django 4.2.6 on 2023-11-10 15:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_rename_items_case_related_for_case_case_related_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case_fir',
            old_name='victim_id',
            new_name='victim_name',
        ),
        migrations.RemoveField(
            model_name='case_fir',
            name='case_id',
        ),
        migrations.AddField(
            model_name='case_fir',
            name='brief',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='case_fir',
            name='brief_material',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='case_fir',
            name='crime_type',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='case_fir',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='case_fir',
            name='division',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='case_fir',
            name='file_report_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='case_fir',
            name='occurance_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='case_fir',
            name='upazila',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='case_related',
            name='for_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.case_fir'),
        ),
        migrations.DeleteModel(
            name='Case_description',
        ),
    ]
