# Generated by Django 4.2.6 on 2023-11-10 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_rename_victim_id_case_fir_victim_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_fir',
            name='case_uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile'),
        ),
    ]
