# Generated by Django 4.2.6 on 2023-11-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_case_fir_case_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='witnessinfo',
            name='brief',
            field=models.TextField(null=True),
        ),
    ]
