# Generated by Django 4.2.6 on 2023-11-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_witnessinfo_brief'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crimetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_name', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
