# Generated by Django 4.2.6 on 2023-11-10 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_crimetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_fir',
            name='crime_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.crimetype'),
        ),
    ]
