# Generated by Django 4.2.6 on 2023-11-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_alter_case_fir_crime_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimetype',
            name='crime_name',
            field=models.CharField(default='Murder', max_length=50, null=True),
        ),
    ]
