# Generated by Django 4.2.6 on 2023-11-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_alter_crimetype_crime_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_fir',
            name='crime_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='crimetype',
            name='crime_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
