# Generated by Django 4.2.6 on 2023-11-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_alter_physicalstructure_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='victiminfo',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='physicalstructure',
            name='age',
            field=models.IntegerField(choices=[('MINOR', 'Minor'), ('YOUNG', 'Young'), ('ADULT', 'Adult'), ('AGED', 'Aged')], null=True),
        ),
        migrations.AlterField(
            model_name='physicalstructure',
            name='faceShape',
            field=models.CharField(choices=[('OVAL', 'Oval'), ('ROUND', 'Round'), ('SQUARE', 'Square'), ('HEART', 'Heart'), ('OBLONG', 'Oblong')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='physicalstructure',
            name='facialHair',
            field=models.CharField(choices=[('BEARD', 'Beard'), ('MUSTACHE', 'Mustache'), ('SHAVED', 'Shaved')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='physicalstructure',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHERS', 'Others')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='physicalstructure',
            name='hairColor',
            field=models.CharField(choices=[('BLACK', 'Black'), ('BROWN', 'Brown'), ('BLONDE', 'Blonde')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='physicalstructure',
            name='hairLength',
            field=models.CharField(choices=[('SHORT', 'Short'), ('LONG', 'Long'), ('MEDIUM', 'Medium')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='physicalstructure',
            name='hairStyle',
            field=models.CharField(choices=[('CURLY', 'Curly'), ('STRAIGHT', 'Straight'), ('BALD', 'Bald')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='physicalstructure',
            name='skinTone',
            field=models.CharField(choices=[('BROWNY', 'Browny'), ('BLACKY', 'Black'), ('WHITEY', 'White')], max_length=255, null=True),
        ),
    ]
