# Generated by Django 4.2.6 on 2023-11-12 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_remove_victiminfo_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='witnessinfo',
            name='relationWithVictim',
        ),
    ]
