# Generated by Django 4.2.7 on 2023-11-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0043_criminalprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="criminalprofile",
            name="criminal_img",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="criminalprofile",
            name="criminal_mark_type",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
