# Generated by Django 4.2.7 on 2023-11-18 18:38

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0044_criminalprofile_criminal_img_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="criminalprofile",
            name="criminal_img",
            field=models.ImageField(
                blank=True, null=True, upload_to=myapp.models.filepath
            ),
        ),
    ]
