# Generated by Django 4.2.7 on 2023-11-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0045_alter_criminalprofile_criminal_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="physicalstructure",
            name="age",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="physicalstructure",
            name="faceShape",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="physicalstructure",
            name="facialHair",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="physicalstructure",
            name="gender",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="physicalstructure",
            name="hairColor",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="physicalstructure",
            name="hairLength",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="physicalstructure",
            name="hairStyle",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="physicalstructure",
            name="skinTone",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
