# Generated by Django 4.2.7 on 2023-11-19 10:53

from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0046_alter_physicalstructure_age_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="case_fir",
            name="case_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("On Going", "On Going"),
                    ("Completed", "Completed"),
                ],
                default="Pending",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="UserNotificationPanel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=50, null=True)),
                (
                    "noti_image",
                    models.ImageField(
                        blank=True, null=True, upload_to=myapp.models.filepath
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "for_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.userprofile",
                    ),
                ),
            ],
        ),
    ]
