# Generated by Django 4.2.7 on 2023-11-28 10:29

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0047_case_fir_case_status_usernotificationpanel"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Ques", models.CharField(blank=True, max_length=255)),
                ("Ans", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "pdf",
                    models.FileField(
                        blank=True, null=True, upload_to=myapp.models.filepath
                    ),
                ),
            ],
        ),
    ]
