# Generated by Django 4.2.6 on 2023-11-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_faq_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criminalprofile',
            name='criminal_fir_id',
        ),
        migrations.AddField(
            model_name='criminalprofile',
            name='criminal_firs',
            field=models.ManyToManyField(to='myapp.case_fir'),
        ),
    ]
