# Generated by Django 4.2.6 on 2023-12-02 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_remove_criminalprofile_criminal_firs'),
    ]

    operations = [
        migrations.CreateModel(
            name='emergency_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(blank=True, max_length=255)),
                ('lon', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='criminalprofile',
            name='criminal_firs',
            field=models.ManyToManyField(to='myapp.case_fir'),
        ),
        migrations.CreateModel(
            name='emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_location', models.ManyToManyField(to='myapp.emergency_location')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.userprofile')),
            ],
        ),
    ]
