# Generated by Django 4.2.6 on 2023-12-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_emergency_location_criminalprofile_criminal_firs_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='emergency_location',
        ),
        migrations.AlterField(
            model_name='emergency',
            name='emergency_location',
            field=models.ManyToManyField(to='myapp.mapmarker'),
        ),
    ]
