# Generated by Django 4.2.6 on 2023-12-02 11:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0052_delete_emergency_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='timestamp',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
